spring:
  application:
    name: competition-system-management-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition_system?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: javacppgorust

mybatis:
  mapper-locations: 'classpath*:/**/mapper/**Mapper.xml'
