spring:
#  profiles:
#    active: dev
  application:
    name: competition-system-management-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/competition_system?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: javacppgorust
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


mybatis:
  mapper-locations: 'classpath*:/**/mapper/**Mapper.xml'
  type-aliases-package: com.wly.competition_system_management_backend.model

#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>总页数会查询最后一页 #禁用合理化时，如果pageNum<1或pageNum>总页数会返回空数据
  support-methods-arguments: true

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost